# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='General', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('article', tinymce.models.HTMLField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('featured', models.BooleanField(default=False)),
                ('is_page', models.BooleanField(default=False)),
                ('display_in_navbar', models.BooleanField(default=False)),
                ('feature_rank', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='perks.Category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
