# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perks',
            name='display_in_navbar',
        ),
        migrations.RemoveField(
            model_name='perks',
            name='is_page',
        ),
    ]
