# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/%Y/%m/%d/')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
