# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 06:11
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='pub_date',
        ),
    ]
