# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 06:34
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170825_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
