# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 15:51
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170827_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
