# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170827_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='detail',
            new_name='description',
        ),
    ]
