# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 10:21
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]