# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170821_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
