# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/%Y/%m/%d/'),
        ),
    ]
