# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField(verbose_name='date booked')),
                ('tiem_start', models.TimeField(verbose_name='start time')),
                ('tiem_end', models.TimeField(verbose_name='end time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('meeting_space', 'Meeting Space'), ('teleconference_room', 'Teleconference Room'), ('workspaces', 'Workspaces'), ('misc', 'Misc')], default='Meeting Space', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officespace.Room'),
        ),
    ]
