# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officespace', '0002_auto_20170821_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('meeting_space', 'Meeting Space'), ('releconference_room', 'Teleconference Room'), ('workspaces', 'Workspaces'), ('misc', 'Misc')], default='Meeting Space', max_length=100),
        ),
    ]
