# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officespace', '0002_auto_20170821_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_start',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_book',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_book',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Meeting Space', 'Meeting Space'), ('Teleconference Room', 'Teleconference Room'), ('Workspaces', 'Workspaces'), ('Misc', 'Misc')], default='Meeting Space', max_length=100),
        ),
    ]
