# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='empty', max_length=150),
            preserve_default=False,
        ),
    ]
