# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='article_text',
        ),
    ]
