# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_text',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
