# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170722_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/%d/'),
        ),
    ]
