# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170722_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/%d/'),
        ),
    ]
