# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 07:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
