# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='feature_rank',
            field=models.IntegerField(default=0),
        ),
    ]
