# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='news.Category'),
        ),
    ]
