# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20170821_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='display_in_navbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_page',
            field=models.BooleanField(default=False),
        ),
    ]
