# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20170821_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
