# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/%d/'),
        ),
    ]
