# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Industry', max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='admin',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(to='community.Category'),
        ),
    ]
