# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/%Y/%m/%d/'),
        ),
    ]
