# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitation_status',
            field=models.BooleanField(default=False),
        ),
    ]
