# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20170820_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
