# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
