# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20170919_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invitation_status',
            field=models.BooleanField(default=False),
        ),
    ]
