# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20170906_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weibo',
        ),
    ]
