# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20170920_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
