# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_profile_weibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advisor',
            field=models.BooleanField(default=False),
        ),
    ]
